### ISSUE TITLE
Bolth running fixtures

### ISSUE THREAD

**Issue by danielcompton** [yeller/bolth#10]
It seems like bolth doesn't run fixtures as part of its test runs. Is that accurate? Is that behaviour intended, or is this a missing feature?

**Comment by danielcompton** [comment]
It looks like they're meant to be run https://github.com/yeller/bolth/blob/master/src/bolth.clj#L53-L54, this seems like a bug. To reproduce, write a test with a fixture that throws an exception. Running `lein test` the error will get thrown, running `script/test` no exception will be thrown and fixture isn't executed.

**Comment by tom-pang** [comment]
Fixed in https://github.com/yeller/bolth/commit/323532683e3f66ae11566db5423c1e927e51818e
