### ISSUE TITLE
Grenchman requirement seems a burden

### ISSUE THREAD

**Issue by mlakewood** [yeller/bolth#2]
The example script uses grenchman, which as of this issue

https://github.com/technomancy/grenchman/issues/30

Is unable to be downloaded in binary format. And the build instructions suggest that to build grenchman from source is a pain. Perhaps a work around could be suggested?

**Comment by tom-pang** [comment]
Hi! Thanks for the heads up - I've been using the same binary I downloaded ages ago, and wasn't aware of this issue.

You could use your editor to fire the same commands into a repl, e.g. vim-fireplace or cider or whatever. The delivery mechanism isn't important.

**Comment by mlakewood** [comment]
Ahh ok. I thought that might be the case. But thought that perhaps maybe the documentation should be updated with instructions to reflect this.

**Comment by danielcompton** [comment]
Grenchman now has binaries available, so this can probably be closed.
