### ISSUE TITLE
tools.namespace is a dev dependency, but required in main code

### ISSUE THREAD

**Issue by danielcompton** [yeller/bolth#4]
I'm getting an error in [`pretty-refresh`](https://github.com/yeller/bolth/blob/master/src/bolth.clj#L400), I suspect this is because tools.namespace is a dev dependency. Should it be a main dependency?

```
java.io.FileNotFoundException: Could not locate clojure/tools/namespace/repl__init.class or clojure/tools/namespace/repl.clj on classpath:
```

**Comment by tom-pang** [comment]
that was originally to let users use the lib without depending on tools namespace, but in bolth2 (see the branch), I've made it a real dependency (that branch is still WIP, though I've been using it in Yeller for a few weeks now).

**Comment by tom-pang** [comment]
Fixed in bolth2
