### ISSUE TITLE
Option to skip slow tests

### ISSUE THREAD

**Issue by danielcompton** [yeller/bolth#8]
There are some tests in codebases which are inherently slow, like test.checking with a large number of cases. Is it possible (or advisable) to have a skip slow tests mode which only runs tests that execute in under n ms?

**Comment by tom-pang** [comment]
@danielcompton this is very possible with the full recording stuff that came in in bolth2 (see the branch under that name). I'm kinda loathe to support it out of the box - I fundamentally believe slow tests are a bad idea to even have in your codebase. bolth2 supports configurable test ordering - you can pass a function in that transforms the order tests run in. It'd be relatively easy to have that thing exclude your slow tests (but bolth2 is still a WIP, and the interface there isn't nailed down).

For Yeller, I set the number of `test.check` iterations dynamically (I have a tiny wrapper around bolth that lives in `user.clj` that lets me set this from an option), and set it to `1` in the dev environment, and scale it up in CI (actually on a bigger CI box that I point against master once a day, I run the test.check tests for a full 6 hours or so). I disagree a bunch with `test.check` forcing you to set iterations on each `defspec` - you really want that stuff controlled at the runner level.
